# Generated by Django 4.0.3 on 2023-07-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creat_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='creat_data',
            new_name='create_data',
        ),
    ]
