# Generated by Django 4.0.3 on 2023-07-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_creat_date_answer_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
